// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsZBrFRURGCzz3ZJ-la-KfvgO9FoFOeI',
    appId: '1:899778873:web:733c6c075e2245182d00e8',
    messagingSenderId: '899778873',
    projectId: 'moneytracker-e43ad',
    authDomain: 'moneytracker-e43ad.firebaseapp.com',
    storageBucket: 'moneytracker-e43ad.appspot.com',
    measurementId: 'G-127FG2J77P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBspZeSFls76b2ky3PF1HcNvIGizO7DTe4',
    appId: '1:899778873:android:9f1372ee48d13dc32d00e8',
    messagingSenderId: '899778873',
    projectId: 'moneytracker-e43ad',
    storageBucket: 'moneytracker-e43ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGZLc_mKjWW3Z0PMTIlQQjVI4mEy4I44',
    appId: '1:899778873:ios:6bd9c6998c23814d2d00e8',
    messagingSenderId: '899778873',
    projectId: 'moneytracker-e43ad',
    storageBucket: 'moneytracker-e43ad.appspot.com',
    iosClientId: '899778873-tnlsrp2ada8qmbbjqo3etkm469krr5uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGZLc_mKjWW3Z0PMTIlQQjVI4mEy4I44',
    appId: '1:899778873:ios:6bd9c6998c23814d2d00e8',
    messagingSenderId: '899778873',
    projectId: 'moneytracker-e43ad',
    storageBucket: 'moneytracker-e43ad.appspot.com',
    iosClientId: '899778873-tnlsrp2ada8qmbbjqo3etkm469krr5uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );
}
